name: model training 
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          dvc remote modify filterout --local gdrive_service_account_json_file_path /dev/null
          dvc pull -r filterout --verbose
          dvc repro
          dvc pull 
          python randomForest.py
          
          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "## Data viz" >> report.md
          cml-publish model.png --md >> report.md
          cml-publish residuals.png --md >> report.md
          
          cml-send-comment report.md